runtime: python310
app_engine_apis: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /public/
  static_dir: public

- url: /assets/
  static_dir: assets
